language: generic

sudo: required

services:
    - docker

before_install:
    - docker build  -t mfsigourav/docker-react -f Dockerfile.dev .

script:
    - docker run mfsigourav/docker-react npm run test -- --coverage
